# Generated by Django 5.2.11 on 2026-02-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='component',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='前端组件路径'),
        ),
        migrations.AddField(
            model_name='permission',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='菜单图标'),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
        migrations.AddField(
            model_name='permission',
            name='redirect',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='重定向路径'),
        ),
        migrations.AddField(
            model_name='permission',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序顺序'),
        ),
    ]
