# Generated by Django 5.2.11 on 2026-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_data_permission_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('createBy', models.CharField(default='admin', max_length=50, verbose_name='创建人')),
                ('updateBy', models.CharField(default='admin', max_length=50, verbose_name='更新人')),
                ('remark', models.CharField(default='remark', max_length=50, verbose_name='评论')),
                ('ipAddress', models.CharField(max_length=50, verbose_name='ip地址')),
                ('userId', models.IntegerField(default=0, unique=True, verbose_name='用户id')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='设备类型')),
                ('isOpenAddFriend', models.BooleanField(default=False, verbose_name='是否开启添加好友')),
                ('isOpenSearchAddFriend', models.BooleanField(default=False, verbose_name='是否开启搜索好友')),
                ('isOpenBookAddFriend', models.BooleanField(default=False, verbose_name='是否开启通讯录加好友')),
                ('isOpenSendFile', models.BooleanField(default=False, verbose_name='是否开启发送文件')),
                ('addNumber', models.IntegerField(default=1, verbose_name='添加好友数量')),
                ('openSendFileIndex', models.IntegerField(default=1, verbose_name='发送文件的索引默认第一个')),
                ('delayTime', models.IntegerField(default=1, verbose_name='发消息间隔延迟时间/s')),
                ('timeIntervalAdd', models.IntegerField(default=5, verbose_name='添加好友间隔延迟时间/s')),
                ('replyContent', models.CharField(default='', max_length=255, verbose_name='加好友话术')),
                ('configType', models.CharField(default='', max_length=50, verbose_name='配置类型')),
                ('addPeopleContent', models.TextField(default='', verbose_name='发消息内容')),
                ('startTime', models.CharField(default='', max_length=25, verbose_name='定时启动时间')),
                ('endTime', models.CharField(default='', max_length=25, verbose_name='定时结束时间')),
                ('isOpenMsgReply', models.BooleanField(default=False, verbose_name='是否开启消息回复')),
                ('status', models.BooleanField(default=False, verbose_name='脚本配置状态 是否开启此脚本')),
            ],
            options={
                'verbose_name': '脚本配置',
                'verbose_name_plural': '脚本配置',
                'db_table': 'script_table',
            },
        ),
    ]
