# Generated by Codex on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripttable',
            name='name',
            field=models.CharField(max_length=50, verbose_name='设备类型'),
        ),
    ]
