# Generated by Codex on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0002_remove_script_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripttable',
            name='replyContent',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='加好友话术'),
        ),
        migrations.AlterField(
            model_name='scripttable',
            name='addPeopleContent',
            field=models.TextField(blank=True, default='', verbose_name='发消息内容'),
        ),
    ]
