# Generated by Codex on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0003_allow_blank_reply_and_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='队列名称')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('count', models.IntegerField(default=0, verbose_name='数据数量')),
                ('created_by', models.CharField(default='', max_length=50, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '脚本队列',
                'verbose_name_plural': '脚本队列',
                'db_table': 'script_queue',
            },
        ),
    ]
